name: gini
description: "Application Star Wars avec SWAPI"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  provider: ^6.1.1
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  flutter_animate: ^4.5.0
  google_fonts: ^6.2.0
  flutter_spinkit: ^5.2.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
  
  # DÃ©claration de la police News Gothic Extra Condensed Regular
  fonts:
    - family: NewsGothicExtraCondensed
      fonts:
        - asset: assets/fonts/News Gothic Extra Condensed Regular.otf
          weight: 400
